---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - rds:
        command: delete
        instance_name: "{{db_name}}"
        region: "{{aws_region}}"
    - rds_subnet_group:
        state: absent
        name: boxfuse-db-subnet-group
        region: "{{aws_region}}"
    - ec2_group:
        name: boxfuse_db_security_group
        description: boxfuse db security group
        region: "{{aws_region}}"
        state: absent
    - ec2_vpc_net:
        name: "boxfuse_vpc"
        cidr_block: 10.0.1.0/24
        region: "{{aws_region}}"
        state: absent
    - ec2_vpc_subnet_facts:
        region: "{{aws_region}}"
        filters:
          "tag:Name": boxfuse_vpc_subnet1
      register: subnet1_facts
    - debug:
        msg: "{{ subnet1_facts }}"
    - ec2_vpc_subnet:
        region: "{{aws_region}}"
        state: absent
        vpc_id: "{{ subnet1_facts.subnets[0].vpc_id }}"
        cidr: 10.0.1.0/24
      when: subnet1_facts.subnets|length > 0
    - ec2_vpc_subnet_facts:
        region: "{{aws_region}}"
        filters:
          "tag:Name": boxfuse_vpc_subnet2
      register: subnet2_facts
    - debug:
        msg: "{{ subnet2_facts }}"
    - ec2_vpc_subnet:
        region: "{{aws_region}}"
        state: absent
        vpc_id: "{{ subnet2_facts.subnets[0].vpc_id }}"        
        cidr: 10.0.2.0/24
      when: subnet1_facts.subnets|length > 0
    - ec2_vpc_net_facts:
        region: "{{aws_region}}"
        filters:
          "tag:Name": boxfuse_vpc
      register: vpc_facts
    - debug:
        msg: "{{ vpc_facts }}"
    - ec2_vpc_igw:
        vpc_id: "{{vpc_facts.vpcs[0].id}}"
        region: "{{aws_region}}"
        state: absent
    - ec2_vpc_net:
        name: "boxfuse_vpc"
        cidr_block: 10.0.0.0/16
        region: "{{aws_region}}"
        state: absent
